# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc483b8ac00e711cf21de456d66da475f1a5557b82c8e67ee0b0cfbea4663ca87593dc0c3303813088d6cb40fb7d0e2036ec68f858f439913f56c41692a07ae

test:
  secret_key_base: 4138264de4d7b5dd94cab7f73b33a6e7783338cc81037f3f3d73d13ba891de7d6d5f33f685f5ea0f28f814621ca652dbe0eabe715c083f4cfeedbabf91f33359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
